export const CATEGORIES = [
  { name: 'Crochet Bouquets & Flowers', slug: 'bouquets-flowers', emoji: '💐', description: 'Eternal blooms that never wilt', color: 'bg-pink-50 dark:bg-pink-950/30', accent: 'text-pink-500' },
  { name: 'Keychains & Bag Charms', slug: 'keychains-charms', emoji: '🔑', description: 'Tiny treasures for every bag', color: 'bg-purple-50 dark:bg-purple-950/30', accent: 'text-purple-500' },
  { name: 'Earrings & Jewelry', slug: 'earrings-jewelry', emoji: '👂', description: 'Handcrafted to adorn', color: 'bg-blue-50 dark:bg-blue-950/30', accent: 'text-blue-500' },
  { name: 'Gift Hampers & Combos', slug: 'gift-hampers', emoji: '🎁', description: 'Curated with love', color: 'bg-amber-50 dark:bg-amber-950/30', accent: 'text-amber-500' },
  { name: 'Amigurumi (Stuffed Toys)', slug: 'amigurumi', emoji: '🧸', description: 'Adorable crocheted companions', color: 'bg-orange-50 dark:bg-orange-950/30', accent: 'text-orange-500' },
  { name: 'Home Décor', slug: 'home-decor', emoji: '🏠', description: 'Coasters, wall art & more', color: 'bg-teal-50 dark:bg-teal-950/30', accent: 'text-teal-500' },
  { name: 'Bookmarks & Accessories', slug: 'bookmarks', emoji: '📚', description: 'Mark your story in style', color: 'bg-green-50 dark:bg-green-950/30', accent: 'text-green-500' },
  { name: 'Wearables', slug: 'wearables', emoji: '🧣', description: 'Scrunchies, headbands & more', color: 'bg-rose-50 dark:bg-rose-950/30', accent: 'text-rose-500' },
];

export const TESTIMONIALS = [
  { id: 1, name: 'Priya Sharma', location: 'Mumbai', rating: 5, text: 'The crochet bouquet I ordered was absolutely stunning! My friend cried happy tears when she received it as a birthday gift. The quality is incredible. Will definitely order again!', avatar: 'PS', product: 'Rose Bouquet', date: '2 weeks ago' },
  { id: 2, name: 'Ananya Gupta', location: 'Delhi', rating: 5, text: 'Ordered the Diwali gift hamper and it was perfect! The packaging was beautiful and the products looked even better in person. Everyone at the party loved them. 10/10!', avatar: 'AG', product: 'Diwali Gift Hamper', date: '1 month ago' },
  { id: 3, name: 'Meera Pillai', location: 'Bangalore', rating: 5, text: "I've been wearing the sunflower earrings almost every day since they arrived. So lightweight and beautifully made! Got so many compliments.", avatar: 'MP', product: 'Sunflower Earrings', date: '3 weeks ago' },
  { id: 4, name: 'Kavita Reddy', location: 'Hyderabad', rating: 5, text: 'The amigurumi teddy bear I got for my daughter is her favorite toy now! She sleeps with it every night. The stitching is so neat. Thank you!', avatar: 'KR', product: 'Amigurumi Teddy Bear', date: '1 week ago' },
  { id: 5, name: 'Sneha Joshi', location: 'Pune', rating: 5, text: 'Got custom name keychains for my whole family! The seller was so responsive and delivered before the deadline. Absolute gem of a shop!', avatar: 'SJ', product: 'Custom Name Keychain', date: '2 months ago' },
];

export const SAMPLE_PRODUCTS = [
  { id: 'prod_001', timestamp: new Date(Date.now() - 2*86400000).toISOString(), name: 'Crochet Bunny Keychain', slug: 'crochet-bunny-keychain', category: 'Keychains & Bag Charms', short_description: 'Adorable hand-crocheted bunny keychain. Perfect for bags, keys, and gifting!', description: 'Meet our most beloved keychain — the Crochet Bunny! Hand-crafted with soft cotton yarn, this little bunny will be the cutest addition to your keys or bag. Each bunny is made with care and comes with floppy ears, a tiny cotton tail, and a sturdy metal key ring.', price: 199, mrp: 249, image1: 'https://images.unsplash.com/photo-1558171813-1ee3f18f10c9?w=600&q=80', image2: 'https://images.unsplash.com/photo-1578301978018-3005759f48f7?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE001', link_meesho: 'https://meesho.com/EXAMPLE001', stock_status: 'In Stock', quantity: 5, is_bestseller: false, is_featured: true, is_visible: true, material: '100% Cotton Yarn', dimensions: '8cm tall (without key ring)', care_instructions: 'Spot clean only. Do not machine wash.', tags: 'keychain, bunny, cute, gift' },
  { id: 'prod_002', timestamp: new Date(Date.now() - 5*86400000).toISOString(), name: 'Rose Bouquet (6 Roses)', slug: 'rose-bouquet-6-roses', category: 'Crochet Bouquets & Flowers', short_description: 'A stunning bouquet of 6 handcrafted crochet roses that last forever!', description: 'Why give flowers that wilt when you can give roses that last forever? Our handcrafted crochet rose bouquet features 6 perfectly crafted roses made from high-quality yarn. Each rose has detailed petals and comes arranged beautifully with ribbon.', price: 799, mrp: 999, image1: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=600&q=80', image2: 'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE002', link_flipkart: 'https://flipkart.com/EXAMPLE002', link_meesho: 'https://meesho.com/EXAMPLE002', link_etsy: 'https://etsy.com/EXAMPLE002', stock_status: 'In Stock', quantity: 3, is_bestseller: false, is_featured: true, is_visible: true, material: 'Acrylic Yarn, Wire Stems', dimensions: '30cm tall bouquet', care_instructions: 'Keep away from moisture. Dust gently with soft brush.', tags: 'flowers, roses, bouquet, gift, anniversary' },
  { id: 'prod_003', timestamp: new Date(Date.now() - 1*86400000).toISOString(), name: 'Sunflower Drop Earrings', slug: 'sunflower-drop-earrings', category: 'Earrings & Jewelry', short_description: 'Lightweight crochet sunflower earrings. Brighten up any outfit!', description: 'Bring the sunshine wherever you go with our handmade crochet sunflower earrings! Made with ultra-fine thread and hypoallergenic hooks, these earrings are lightweight enough to wear all day.', price: 149, mrp: null, image1: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE003', link_meesho: 'https://meesho.com/EXAMPLE003', stock_status: 'In Stock', quantity: 10, is_bestseller: false, is_featured: false, is_visible: true, material: 'Cotton Thread, Hypoallergenic Hooks', dimensions: '4cm drop length', care_instructions: 'Store in jewelry pouch. Avoid water contact.', tags: 'earrings, jewelry, sunflower, lightweight' },
  { id: 'prod_004', timestamp: new Date(Date.now() - 14*86400000).toISOString(), name: 'Amigurumi Teddy Bear', slug: 'amigurumi-teddy-bear', category: 'Amigurumi (Stuffed Toys)', short_description: "The most huggable hand-crocheted teddy bear. A child's best friend!", description: 'Our Amigurumi Teddy Bear is made with love and soft yarn to create the most huggable companion. Standing at approximately 20cm tall, this teddy features safety eyes and a cute embroidered nose.', price: 599, mrp: 749, image1: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE004', link_flipkart: 'https://flipkart.com/EXAMPLE004', stock_status: 'Out of Stock', quantity: 0, is_bestseller: false, is_featured: false, is_visible: true, material: 'Soft Acrylic Yarn, Safety Eyes, Hypoallergenic Fiberfill', dimensions: '20cm tall (approx)', care_instructions: 'Hand wash gently with mild soap. Air dry flat.', tags: 'teddy bear, amigurumi, stuffed toy, kids' },
  { id: 'prod_005', timestamp: new Date(Date.now() - 20*86400000).toISOString(), name: 'Diwali Gift Hamper', slug: 'diwali-gift-hamper', category: 'Gift Hampers & Combos', short_description: 'A festive hamper packed with handmade crochet goodies. Perfect Diwali gift!', description: 'Celebrate the festival of lights with our exclusive Diwali Gift Hamper! This curated hamper includes a crochet diya cover, 2 mini flower bookmarks, 1 festive keychain, and 1 decorative coaster — all handmade with love.', price: 999, mrp: 1299, image1: 'https://images.unsplash.com/photo-1574169208507-84376144848b?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE005', link_flipkart: 'https://flipkart.com/EXAMPLE005', link_meesho: 'https://meesho.com/EXAMPLE005', stock_status: 'In Stock', quantity: 2, is_bestseller: true, is_featured: true, is_visible: true, material: 'Mixed Yarn, Gift Box', dimensions: 'Box: 25cm x 20cm x 10cm', care_instructions: 'Individual pieces: spot clean only.', tags: 'diwali, gift hamper, festive, combo' },
  { id: 'prod_006', timestamp: new Date(Date.now() - 10*86400000).toISOString(), name: 'Mandala Coaster Set (4 pcs)', slug: 'mandala-coaster-set-4pcs', category: 'Home Décor', short_description: 'Beautiful handcrafted mandala coasters. Protect your surfaces in style!', description: 'Elevate your home décor with our hand-crocheted Mandala Coasters. Each set of 4 features unique mandala patterns in coordinating colors. Made from durable cotton yarn.', price: 349, mrp: 449, image1: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE006', link_meesho: 'https://meesho.com/EXAMPLE006', stock_status: 'In Stock', quantity: 7, is_bestseller: false, is_featured: false, is_visible: true, material: '100% Cotton Yarn', dimensions: '10cm diameter each', care_instructions: 'Machine wash cold, gentle cycle. Air dry.', tags: 'coaster, home decor, mandala, set' },
  { id: 'prod_007', timestamp: new Date(Date.now() - 4*86400000).toISOString(), name: 'Lavender Bloom Bookmark', slug: 'lavender-bloom-bookmark', category: 'Bookmarks & Accessories', short_description: "Delicate crochet lavender bookmark. A reader's best companion!", description: 'For the bookworms who love beautiful things! Our Lavender Bloom Bookmark features a delicate crochet lavender sprig that peeks out from your pages. Made with fine cotton thread.', price: 99, mrp: null, image1: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80', link_meesho: 'https://meesho.com/EXAMPLE007', stock_status: 'In Stock', quantity: 15, is_bestseller: false, is_featured: false, is_visible: true, material: 'Fine Cotton Thread', dimensions: '15cm with tassel', care_instructions: 'Keep dry. Spot clean if needed.', tags: 'bookmark, lavender, reading, book' },
  { id: 'prod_008', timestamp: new Date().toISOString(), name: 'Tulip Single Stem', slug: 'tulip-single-stem', category: 'Crochet Bouquets & Flowers', short_description: 'A single perfect crochet tulip on a wire stem. Simple & elegant!', description: 'Sometimes one perfect flower says it all. Our crochet Tulip Single Stem is hand-crafted with attention to every petal, mounted on a flexible wire stem wrapped in green yarn. Available in pink, red, yellow, and purple.', price: 149, mrp: null, image1: 'https://images.unsplash.com/photo-1490750967868-88df5691cc1e?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE008', link_etsy: 'https://etsy.com/EXAMPLE008', stock_status: 'In Stock', quantity: 20, is_bestseller: false, is_featured: true, is_visible: true, material: 'Yarn, Wire Stem, Green Tape', dimensions: '25cm tall', care_instructions: 'Keep away from water. Dust gently.', tags: 'tulip, flower, stem, elegant' },
  { id: 'prod_009', timestamp: new Date(Date.now() - 7*86400000).toISOString(), name: 'Scrunchie Set (3 pcs)', slug: 'scrunchie-set-3pcs', category: 'Wearables', short_description: 'Handmade crochet scrunchies in 3 coordinating colors. So soft!', description: 'Upgrade your hair game with our handmade crochet scrunchies! Each set includes 3 scrunchies in complementary colors. Made with soft acrylic yarn over elastic, these scrunchies are gentle on hair.', price: 249, mrp: 299, image1: 'https://images.unsplash.com/photo-1590333748338-d629e4564ad9?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE009', link_meesho: 'https://meesho.com/EXAMPLE009', stock_status: 'In Stock', quantity: 8, is_bestseller: false, is_featured: false, is_visible: true, material: 'Soft Acrylic Yarn, Elastic', dimensions: 'Standard size, stretches to fit all', care_instructions: 'Hand wash with mild shampoo. Air dry.', tags: 'scrunchie, hair, wearable, boho, set' },
  { id: 'prod_010', timestamp: new Date(Date.now() - 30*86400000).toISOString(), name: 'Custom Name Keychain', slug: 'custom-name-keychain', category: 'Keychains & Bag Charms', short_description: 'Personalised crochet keychain with your name! Unique & handmade.', description: "The gift that's truly one-of-a-kind! Our Custom Name Keychain is hand-crocheted with your chosen name or initials. Each letter is individually crafted and strung together on a sturdy keyring. Choose from 8 color options.", price: 299, mrp: 349, image1: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80', link_amazon: 'https://amazon.in/dp/EXAMPLE010', link_meesho: 'https://meesho.com/EXAMPLE010', link_etsy: 'https://etsy.com/EXAMPLE010', stock_status: 'In Stock', quantity: null, is_bestseller: true, is_featured: false, is_visible: true, material: 'Cotton Yarn, Metal Key Ring', dimensions: 'Approx 2-3cm per letter', care_instructions: 'Spot clean only.', tags: 'keychain, custom, name, personalised, gift' },
];
